### PR TITLE
Added cleanlooks and dark-orange

### PR DESCRIPTION
**Pull request by Martin-Jung**
Two themes. Cleanlooks still needs a bit of tweaking

### CODE REVIEW

**Comment by NathanW2** [comment]
Seems there is already a plugin at https://github.com/All4Gis/Load-QSS so we can add styles to that.

**Comment by NathanW2** [comment]
No point having two plugins doing the same.  Do you want to transfer the style or I can

**Comment by Martin-Jung** [comment]
Na, please do it. They are not my original work anyway.

**Comment by NathanW2** [comment]
OK I will port them over with credit to you anyway.

**Pull request closed without merging**
